apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: &name install-mlx-driver
  labels:
    app: *name
spec:
  selector:
    matchLabels:
      app: *name
  template:
    metadata:
      labels:
        app: *name
    spec:
      tolerations:
      - key: "sku"
        operator: "Equal"
        value: "gpu"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node.kubernetes.io/instance-type
                operator: In
                values:
                - Standard_ND40rs_v2

      hostNetwork: true
      hostPID: true
      containers:
      - image: ghcr.io/converged-computing/aks-infiniband-install:ubuntu-20.04
        imagePullPolicy: Always
        name: *name
        command: ["/entrypoint.sh"] 
        args: ["installonly"]
        resources:
          requests:
            {}
          limits:
            {}
        securityContext:
          privileged: true
        volumeMounts:
        - name: actions
          mountPath: "/opt/actions"
        - name: hostmount
          mountPath: "/mnt/actions"
        - name: debs
          mountPath: "/mnt/debs"
      volumes:
      - name: debs
        hostPath:
          path: /opt/debs
          type: DirectoryOrCreate
      - name: hostmount
        hostPath:
          path: /opt/actions
          type: DirectoryOrCreate
      - name: actions
        configMap:
          name: install-driver-actions
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: install-driver-actions
  labels:
    app: install-mlx-driver
data:
  installonly: |
    #!/usr/bin/env bash
    set -eo pipefail

    sleep infinity
    umount /mnt/install || true
    cd /opt/debs
    mkdir -p /mnt/install
    mount -o ro,loop ./mlnx-en-4.9-7.1.0.0-ubuntu20.04-x86_64.iso /mnt/install
    /mnt/install/mlnxofedinstall --force
    /etc/init.d/openibd restart
    
    # Read in ip links, rename to ib0, and start
    # ip link set ibP257s75549 name ib0    
    # ip link set ib0 up
    wget https://raw.githubusercontent.com/converged-computing/aks-infiniband-install/main/ubuntu20.04/parse-links.py
    python3 parse-links.py
    ip link
    check_ib="$(ip link | grep ib0)"
    if [ -z "$check_ib" ];
    then
        echo "driver installation failed"
        exit 1
    fi
    echo "installation completed."
    exit 0
