apiVersion: v1
kind: ConfigMap
metadata:
  name: rdma-devices
  namespace: kube-system
data:
  config.json: |
    {
        "periodicUpdateInterval": 300,
        "configList": [{
             "resourceName": "shared_hca_rdma",
             "resourcePrefix": "mellanox.com",
             "rdmaHcaMax": 100,
             "selectors": {
                "ifNames": ["ib0"],
                "drivers": ["mlx5_core"]
             }
           }]
    }
# Note: increase rdmaHcaMax to number of pods deployed on each node if greater than 1
# Since we have 1:1 mapping we want to keep this at 1
  
